export function sanitizeEventData(data: Record<string, any>) {
  return {
    slug: data.slug ? String(data.slug).trim() : undefined,
    brideNameKm: data.brideNameKm ? String(data.brideNameKm) : undefined,
    brideNameEn: data.brideNameEn ? String(data.brideNameEn) : undefined,
    groomNameKm: data.groomNameKm ? String(data.groomNameKm) : undefined,
    groomNameEn: data.groomNameEn ? String(data.groomNameEn) : undefined,
    eventDate: data.eventDate ? new Date(data.eventDate) : undefined,
    eventTime: data.eventTime ? String(data.eventTime) : undefined,
    locationNameKm: data.locationNameKm ? String(data.locationNameKm) : undefined,
    locationNameEn: data.locationNameEn ? String(data.locationNameEn) : undefined,
    locationAddressKm: data.locationAddressKm ? String(data.locationAddressKm) : undefined,
    locationAddressEn: data.locationAddressEn ? String(data.locationAddressEn) : undefined,
    googleMapUrl: data.googleMapUrl && String(data.googleMapUrl).trim() ? String(data.googleMapUrl).trim() : null,
    coverImage: data.coverImage && String(data.coverImage).trim() ? String(data.coverImage).trim() : null,
    invitationMessageKm: data.invitationMessageKm !== undefined ? String(data.invitationMessageKm) : undefined,
    invitationMessageEn: data.invitationMessageEn !== undefined ? String(data.invitationMessageEn) : undefined,
    theme: data.theme ? String(data.theme) : "Classic Khmer Wedding",
    musicUrl: data.musicUrl && String(data.musicUrl).trim() ? String(data.musicUrl).trim() : null,
    optimizedMusicUrl: data.optimizedMusicUrl && String(data.optimizedMusicUrl).trim() ? String(data.optimizedMusicUrl).trim() : null,
    musicTitle: data.musicTitle && String(data.musicTitle).trim() ? String(data.musicTitle).trim() : null,
    heroVideoUrl: data.heroVideoUrl && String(data.heroVideoUrl).trim() ? String(data.heroVideoUrl).trim() : null,
    heroVideoType: data.heroVideoType ? String(data.heroVideoType) : null,
    heroVideoPosterUrl: data.heroVideoPosterUrl && String(data.heroVideoPosterUrl).trim() ? String(data.heroVideoPosterUrl).trim() : null,
    showHeroVideo: Boolean(data.showHeroVideo),
    transitionVideoUrl: data.transitionVideoUrl && String(data.transitionVideoUrl).trim() ? String(data.transitionVideoUrl).trim() : null,
    showTransitionVideo: data.showTransitionVideo !== undefined ? Boolean(data.showTransitionVideo) : true,
    openingImageUrl: data.openingImageUrl && String(data.openingImageUrl).trim() ? String(data.openingImageUrl).trim() : null,
    openingCoupleNamesImageUrl: data.openingCoupleNamesImageUrl && String(data.openingCoupleNamesImageUrl).trim() ? String(data.openingCoupleNamesImageUrl).trim() : null,
    openingTitleKm: data.openingTitleKm && String(data.openingTitleKm).trim() ? String(data.openingTitleKm).trim() : null,
    openingTitleEn: data.openingTitleEn && String(data.openingTitleEn).trim() ? String(data.openingTitleEn).trim() : null,
    openingMessageKm: data.openingMessageKm && String(data.openingMessageKm).trim() ? String(data.openingMessageKm).trim() : null,
    openingMessageEn: data.openingMessageEn && String(data.openingMessageEn).trim() ? String(data.openingMessageEn).trim() : null,
    showOpeningScreen: data.showOpeningScreen !== undefined ? Boolean(data.showOpeningScreen) : true,
    showCurtainIntro: data.showCurtainIntro !== undefined ? Boolean(data.showCurtainIntro) : true,
    curtainIntroType: data.curtainIntroType ? String(data.curtainIntroType) : "css",
    curtainIntroVideoUrl: data.curtainIntroVideoUrl && String(data.curtainIntroVideoUrl).trim() ? String(data.curtainIntroVideoUrl).trim() : null,
    allowSkipCurtainIntro: data.allowSkipCurtainIntro !== undefined ? Boolean(data.allowSkipCurtainIntro) : true,
    galleryImages: data.galleryImages !== undefined ? data.galleryImages : null,
    galleryVideoUrl: data.galleryVideoUrl && String(data.galleryVideoUrl).trim() ? String(data.galleryVideoUrl).trim() : null,

    blessingTitleKm: data.blessingTitleKm && String(data.blessingTitleKm).trim() ? String(data.blessingTitleKm).trim() : null,
    blessingTitleEn: data.blessingTitleEn && String(data.blessingTitleEn).trim() ? String(data.blessingTitleEn).trim() : null,
    groomFatherNameKm: data.groomFatherNameKm && String(data.groomFatherNameKm).trim() ? String(data.groomFatherNameKm).trim() : null,
    groomFatherNameEn: data.groomFatherNameEn && String(data.groomFatherNameEn).trim() ? String(data.groomFatherNameEn).trim() : null,
    groomMotherNameKm: data.groomMotherNameKm && String(data.groomMotherNameKm).trim() ? String(data.groomMotherNameKm).trim() : null,
    groomMotherNameEn: data.groomMotherNameEn && String(data.groomMotherNameEn).trim() ? String(data.groomMotherNameEn).trim() : null,
    brideFatherNameKm: data.brideFatherNameKm && String(data.brideFatherNameKm).trim() ? String(data.brideFatherNameKm).trim() : null,
    brideFatherNameEn: data.brideFatherNameEn && String(data.brideFatherNameEn).trim() ? String(data.brideFatherNameEn).trim() : null,
    brideMotherNameKm: data.brideMotherNameKm && String(data.brideMotherNameKm).trim() ? String(data.brideMotherNameKm).trim() : null,
    brideMotherNameEn: data.brideMotherNameEn && String(data.brideMotherNameEn).trim() ? String(data.brideMotherNameEn).trim() : null,
    formalInvitationTextKm: data.formalInvitationTextKm !== undefined && String(data.formalInvitationTextKm).trim() ? String(data.formalInvitationTextKm) : null,
    formalInvitationTextEn: data.formalInvitationTextEn !== undefined && String(data.formalInvitationTextEn).trim() ? String(data.formalInvitationTextEn) : null,
    couplePhotoUrl: data.couplePhotoUrl && String(data.couplePhotoUrl).trim() ? String(data.couplePhotoUrl).trim() : null,
    coupleMonogramImageUrl: data.coupleMonogramImageUrl && String(data.coupleMonogramImageUrl).trim() ? String(data.coupleMonogramImageUrl).trim() : null,
    showMonogram: Boolean(data.showMonogram),
    showPhotoVideoTransitionVideo: Boolean(data.showPhotoVideoTransitionVideo),
    showTraditionalInvitationSection: data.showTraditionalInvitationSection !== undefined ? Boolean(data.showTraditionalInvitationSection) : true,

    showMapQrCode: data.showMapQrCode !== undefined ? Boolean(data.showMapQrCode) : true,
    showGuestNameInSharePreview: data.showGuestNameInSharePreview !== undefined ? Boolean(data.showGuestNameInSharePreview) : true,
    socialPreviewImageUrl: data.socialPreviewImageUrl && String(data.socialPreviewImageUrl).trim() ? String(data.socialPreviewImageUrl).trim() : null,
    showGiftQrCode: Boolean(data.showGiftQrCode),
    giftQrImageUrl: data.giftQrImageUrl && String(data.giftQrImageUrl).trim() ? String(data.giftQrImageUrl).trim() : null,
    giftQrKhImageUrl: data.giftQrKhImageUrl && String(data.giftQrKhImageUrl).trim() ? String(data.giftQrKhImageUrl).trim() : null,
    giftQrUsdImageUrl: data.giftQrUsdImageUrl && String(data.giftQrUsdImageUrl).trim() ? String(data.giftQrUsdImageUrl).trim() : null,
    giftQrTitleKm: data.giftQrTitleKm && String(data.giftQrTitleKm).trim() ? String(data.giftQrTitleKm).trim() : null,
    giftQrTitleEn: data.giftQrTitleEn && String(data.giftQrTitleEn).trim() ? String(data.giftQrTitleEn).trim() : null,
    giftQrNoteKm: data.giftQrNoteKm && String(data.giftQrNoteKm).trim() ? String(data.giftQrNoteKm).trim() : null,
    giftQrNoteEn: data.giftQrNoteEn && String(data.giftQrNoteEn).trim() ? String(data.giftQrNoteEn).trim() : null,
    giftBankName: data.giftBankName && String(data.giftBankName).trim() ? String(data.giftBankName).trim() : null,
    giftAccountName: data.giftAccountName && String(data.giftAccountName).trim() ? String(data.giftAccountName).trim() : null,
    giftAccountNumber: data.giftAccountNumber && String(data.giftAccountNumber).trim() ? String(data.giftAccountNumber).trim() : null,
    giftKhBankName: data.giftKhBankName && String(data.giftKhBankName).trim() ? String(data.giftKhBankName).trim() : null,
    giftKhAccountName: data.giftKhAccountName && String(data.giftKhAccountName).trim() ? String(data.giftKhAccountName).trim() : null,
    giftKhAccountNumber: data.giftKhAccountNumber && String(data.giftKhAccountNumber).trim() ? String(data.giftKhAccountNumber).trim() : null,
    giftUsdBankName: data.giftUsdBankName && String(data.giftUsdBankName).trim() ? String(data.giftUsdBankName).trim() : null,
    giftUsdAccountName: data.giftUsdAccountName && String(data.giftUsdAccountName).trim() ? String(data.giftUsdAccountName).trim() : null,
    giftUsdAccountNumber: data.giftUsdAccountNumber && String(data.giftUsdAccountNumber).trim() ? String(data.giftUsdAccountNumber).trim() : null,

    showThankYouLetter: data.showThankYouLetter !== undefined ? Boolean(data.showThankYouLetter) : true,
    thankYouTitleKm: data.thankYouTitleKm && String(data.thankYouTitleKm).trim() ? String(data.thankYouTitleKm).trim() : null,
    thankYouTitleEn: data.thankYouTitleEn && String(data.thankYouTitleEn).trim() ? String(data.thankYouTitleEn).trim() : null,
    thankYouTextKm: data.thankYouTextKm !== undefined && String(data.thankYouTextKm).trim() ? String(data.thankYouTextKm) : null,
    thankYouTextEn: data.thankYouTextEn !== undefined && String(data.thankYouTextEn).trim() ? String(data.thankYouTextEn) : null,

    showApologyLetter: data.showApologyLetter !== undefined ? Boolean(data.showApologyLetter) : true,
    apologyTitleKm: data.apologyTitleKm && String(data.apologyTitleKm).trim() ? String(data.apologyTitleKm).trim() : null,
    apologyTitleEn: data.apologyTitleEn && String(data.apologyTitleEn).trim() ? String(data.apologyTitleEn).trim() : null,
    apologyTextKm: data.apologyTextKm !== undefined && String(data.apologyTextKm).trim() ? String(data.apologyTextKm) : null,
    apologyTextEn: data.apologyTextEn !== undefined && String(data.apologyTextEn).trim() ? String(data.apologyTextEn) : null,
  };
}
